# .streamlit/secrets.toml
[connections.gsheets]
#spreadsheet = "https://docs.google.com/spreadsheets/d/xxxxxxx/edit#gid=0"


spreadsheet = "https://docs.google.com/spreadsheets/d/10e1JfvNTklFXhhYsnNMiAUSmKoMSrDI9H5B4zmuAyN4/edit#gid=0" #pet.ss
# spreadsheet = "https://docs.google.com/spreadsheets/d/14NnFwGpqz7S-abVu3cZX0csPZEX52HDUVn0OkSuZaK8/edit?usp=sharing" #pref2.ss

# spreadsheet = "https://docs.google.com/spreadsheets/d/1NRKA1gbs0qEJ4gwWQIScNTOjBC2QjdzjM9G_Uu2q8Hg/edit?usp=drive_link" #ポスター掲示推進_料理店（交渉・掲示状況管理）リスト.ss